### PR TITLE
Re enable features

### PR DESCRIPTION
**Pull request by makaimann**
Add back some features that were removed temporarily and fix configurations

### CODE REVIEW

**Comment by ahmed-irfan** [comment]
are we going to merge this?

**Comment by makaimann** [comment]
I'm not sure yet. Do you think we should evaluate it more first?

**Comment by ahmed-irfan** [comment]
i want this https://github.com/makaimann/prophic3/pull/36/files#diff-24291604882058303989f62447f8c16dR87 to be merged. Not sure about the remaining

**Comment by makaimann** [comment]
Makes sense! I reverted the index flattening which is what I'm not sure about and made a separate PR for that which we can wait to merge: https://github.com/makaimann/prophic3/pull/38

We can merge this if you think it's ready.

**Pull request merged**
